# tasks/main.yml
---
- name: Check current Docker containers for port conflicts
  command: docker ps --format "{{.Ports}}"
  register: docker_ports
  changed_when: false

- name: Set available port
  set_fact:
    available_port: "{{ item }}"
  vars:
    port_range: "{{ range(docker_port_range.split('-')[0]|int, docker_port_range.split('-')[1]|int + 1)|list }}"
  loop: "{{ port_range }}"
  when: >
    docker_ports.stdout_lines | select("search", "0.0.0.0:{{ item }}") | length == 0
  register: result

- name: Fail if no port is available
  fail:
    msg: "No available port found in range {{ docker_port_range }}"
  when: available_port is not defined

- name: Pull Docker image
  docker_image:
    name: "{{ docker_image }}"
    tag: "{{ docker_tag }}"
    source: pull

- name: Run Docker container
  docker_container:
    name: petclinic
    image: "{{ docker_image }}:{{ docker_tag }}"
    state: started
    restart_policy: always
    published_ports:
      - "{{ available_port }}:8081"

- name: Check running Docker containers
  command: docker ps
  register: docker_ps
  changed_when: false

- name: Print running Docker containers
  debug:
    msg: "{{ docker_ps.stdout }}"